##################
#  Input section  #
###################
[input]
### TLS, not using coroutines
type = "tcp"
format = "gelf"
listen = "0.0.0.0:22202"
framing = "nul"
tcp_threads = 2

####################
#  Output section  #
####################
[output]
### Debug output (stdout)
#type = "stdout"

### Kafka output
type = "kafka"
topic = "alpha.log1"

### Output format and parameters
### JSON (GELF)
format = "gelf"

[output.gelf_extra]
X-OVH-INPUT = "gelf-clear"

[output.librdkafka]
"bootstrap.servers" = "kafka-1.alpha.thot.ovh.com:9094,kafka-2.alpha.thot.ovh.com:9094"
"produce.offset.report" = "true"
"message.timeout.ms" = "30000"
"request.required.acks" = "0"
"compression.codec" = "gzip"